# Generated by Django 3.0.4 on 2020-04-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_songs_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('genre', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
